## Arrays and Vectorized

### 1. 기본 특징:
1. N차원 배열 만들어줌
2. 시간복잡도 생각 안하고 O(1)로 배열 접근 가능
3. 선형대수 잘 모름 일단 좋음
4. Numpy를 C, C++ 또는 FORTRAN이랑 연결하기 좋음

### 1.1. 속도
numpy는 기본 파이썬보다 약 10~100배 더 빠른 속도를 보여줌

In [74]:
import numpy as np

my_arr = np.arange(1_000_000) # 언더바는 가독성을 위한 요소일 뿐 코드에 직접적인 영향은 없음
# vector<int> my_arr(100000, i); 비슷함. 0 ~ 999,999 의 정수를 가진 배열을 만듦.
my_list = list(range(1_000_000))
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]
# %timeit 은 벤치마크 도구임 실행 시간을 통계적으로 재는 매직 커맨드임
# [x * 2 for x in my_list] 는 리스트 컴프리헨션이다.  [표현식 for 항목 in iterable if 조건] 도 가능하다
my_list3 = [x * 2 for x in my_list if x % 10 == 0]
print(my_list3[:10])

2.63 ms ± 55.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
60.3 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
[0, 20, 40, 60, 80, 100, 120, 140, 160, 180]


In [75]:
import numpy as np

data = np.array([[1, 2, 3], [1.5, 0, -3]])
print(data)
# 줄바꿈이 자동으로 들어가서 2차원 배열이 잘 표현됨

data = data * 10
print(data)

data = data + data
print(data)

data.shape
# 2행 3열의 배열
data.dtype # datatype


[[ 1.   2.   3. ]
 [ 1.5  0.  -3. ]]
[[ 10.  20.  30.]
 [ 15.   0. -30.]]
[[ 20.  40.  60.]
 [ 30.   0. -60.]]


dtype('float64')

In [76]:
# 스칼라 요소 간의 연산..? 무튼 수학적 연산에 도움을 줌
data1 = [1, 2, 3, 4]
data2 = [[1, 2, 3,], [10, 9, 8]]
data3 = [[1, 2, 3, 4], ['t', 'e', 's', 't']]


my_arr1 = np.array(data1)
my_arr2 = np.array(data2)
my_arr3 = np.array(data3)

# print(my_arr1)
# print(my_arr2)
# print(my_arr3)

# print(my_arr1.ndim) # N dimension, N 차원
# print(my_arr1.shape)
# print(my_arr2.dtype)
# print(my_arr2.shape)

print(f"{my_arr1.ndim}차원 배열\n데이터 타입:{my_arr1.dtype}\n")
print(f"{my_arr2.ndim}차원 배열\n데이터 타입:{my_arr2.dtype}\n{my_arr2.shape}의 크기를 가졌다.\n")
print(f"{my_arr3.ndim}차원 배열\n데이터 타입:{my_arr3.dtype}\n{my_arr3.shape}의 크기를 가졌다.\n")

1차원 배열
데이터 타입:int64

2차원 배열
데이터 타입:int64
(2, 3)의 크기를 가졌다.

2차원 배열
데이터 타입:<U21
(2, 4)의 크기를 가졌다.



In [77]:
my_arr1 = np.zeros(10)
# vector<int> my_arr(10, 0); 과 비슷함. 10개의 요소를 가진 배열을 만들고 모든 요소는 0으로 초기화
print(my_arr1)

my_arr2 = np.zeros((3, 6))
print(my_arr2) # 3행 6열의 배열을 만들고 모든 요소는 0으로 초기화

my_arr3 = np.ones((2, 2, 2))
print(my_arr3) # 2행 2열 2면의 배열을 만들고 모든 요소는 1로 초기화

my_arr4 = np.empty((2, 3))
print(my_arr4) # 2행 3열의 배열을 만들지만 쓰레기 값을 가지고 있음


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-323 4.4e-323 4.0e-323]]


In [78]:
print(np.arange(15))
print(list(range(0, 15)))



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


#### Array
입력 데이터(리스트, 튜플, 배열 또는 기타 시퀀스)를 데이터 유형을 추론하거나, 지정하여 N차 배열로 변환함. 입력 데이터를 복사함. array(시퀀스)
#### Asarray
입력값을 N차 배열로 변환하되, 입력값이 이미 N차 배열이면 새로 안 만듦. 불필요한 복사하지 않고 그대로 쓴다. asarray(시퀀스)
#### Arange
range랑 비슷한데 return 값이 리스트가 아니고 N차 배열 형태로 반환함. arange(입력값)
#### Full, Full_like
주어진 형태와 데이터 타입을 가진 배열 생성 후 입력받은 값으로 가득 채움 full(형태, 입력값)
#### Eye, identify
대각선에 1, 나머지는 모두 0인 N*N 크기의 정사각형 행렬
#### Zeros, zeros_like | Ones, ones_like

In [90]:
data = [[1,2,3], [4,5,6]]
a = np.array(data)
b = np.ones_like(a)
c = np.ones(a.shape)
print(b)
print(c)
d = np.full(a.shape, 5);
print(d)
e = np.eye(3)
print(e)
f = np.identity(3)
print(f)

[[1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### N차원 배열의 데이터 유형
#### Astype()
.astype() 은 N차원 배열의 데이터를 입력받은 데이터 유형으로 변경해줌.
1.25, -9.6, 42 이라는 dtype=str 값이 들어오고 이를 int 형식으로 바꾸려면
dtype=str 을 float16 으로 변경하고 그 후에 int를 바꿔야함. (그러지 않음 ValueError를 일으킴)



64 배정밀
32 단정밀
16 반정밀

In [152]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr3 = np.array([1, 2, 3], dtype=np.uint8)

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr = arr.astype(np.int32)
print(arr)
print("ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ")
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=str)
print(numeric_strings)
numeric_strings = numeric_strings.astype(np.float16)
print(numeric_strings)
numeric_strings = numeric_strings.astype(np.int16)
print(numeric_strings)

int_array = np.arange(10) # 0 ~ 9 까지 배열 만듦
print(int_array)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
# float64 의 배열을 만듦
print(calibers)
calibers = calibers.astype(np.int32) # float64를 int32로 변환
int_array = int_array.astype(calibers.dtype) # int를 calibers의 데이터 타입으로 변환
print(int_array.dtype)

# 약식코드 사용
all_zero_array = np.zeros(10, dtype="u4") # u4 = int32, uint32
print(all_zero_array)
all_one_array = np.ones(5, dtype=np.uint32)
print(all_one_array)

float64
int32
uint8
[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
['1.25' '-9.6' '42']
[ 1.25 -9.6  42.  ]
[ 1 -9 42]
[0 1 2 3 4 5 6 7 8 9]
[0.22  0.27  0.357 0.38  0.44  0.5  ]
int32
[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1]


### Numpy 배열 산술 연산


#### .1. 사칙연산

In [157]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr) # element-wise 곱셈
print(arr - arr) # element-wise 뺄셈
# 계산은 순차적으로 진행됨

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]


[^1] element-wise: 요소별 계산

#### .2. 비교연산

In [169]:
arr1 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 = np.array([[0., 3., 10.], [6., 2., 12.]])
print(arr1)
print(arr2, "\n")

print("arr1 < arr2")
print(arr1 < arr2)
print("arr1 > arr2")
print(arr1 > arr2)
print("arr1 == arr2")
print(arr1 == arr2)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[ 0.  3. 10.]
 [ 6.  2. 12.]] 

arr1 < arr2
[[False False  True]
 [False False False]]
arr1 > arr2
[[False  True False]
 [ True False False]]
arr1 == arr2
[[ True False False]
 [False  True  True]]


### 인덱싱 및 슬라이싱

In [178]:
arr = np.arange(10)
print(arr)

print(arr[2])
print(arr[:3])
print(arr[5:9])
print(arr[3:])

arr_sliced = arr[6:10]
print(arr_sliced)

[0 1 2 3 4 5 6 7 8 9]
2
[0 1 2]
[5 6 7 8]
[3 4 5 6 7 8 9]
[6 7 8 9]
