## Arrays and Vectorized

In [73]:
print('''
기본 특징:
N차원 배열을 지원함
반복문 없이 전체 배열에 빠르게 접근 가능함
선형대수, 난수 생성
디스크에 배열 데이터를 읽고 쓰고 메모리 매핑?
NumPy를 C 혹은 C++, Fortran으로 작성된 라이브러리로 구현하여 빠른 속도 제공''')


기본 특징:
N차원 배열을 지원함
반복문 없이 전체 배열에 빠르게 접근 가능함
선형대수, 난수 생성
디스크에 배열 데이터를 읽고 쓰고 메모리 매핑?
NumPy를 C 혹은 C++, Fortran으로 작성된 라이브러리로 구현하여 빠른 속도 제공


In [74]:
import numpy as np

my_arr = np.arange(1_000_000) # 언더바는 가독성을 위한 요소일 뿐 코드에 직접적인 영향은 없음
# vector<int> my_arr(100000, i); 비슷함. 0 ~ 999,999 의 정수를 가진 배열을 만듦.
my_list = list(range(1_000_000))
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]
# %timeit 은 벤치마크 도구임 실행 시간을 통계적으로 재는 매직 커맨드임
# [x * 2 for x in my_list] 는 리스트 컴프리헨션이다.  [표현식 for 항목 in iterable if 조건] 도 가능하다
my_list3 = [x * 2 for x in my_list if x % 10 == 0]
print(my_list3[:10])

2.63 ms ± 55.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
60.3 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
[0, 20, 40, 60, 80, 100, 120, 140, 160, 180]


In [75]:
import numpy as np

data = np.array([[1, 2, 3], [1.5, 0, -3]])
print(data)
# 줄바꿈이 자동으로 들어가서 2차원 배열이 잘 표현됨

data = data * 10
print(data)

data = data + data
print(data)

data.shape
# 2행 3열의 배열
data.dtype # datatype


[[ 1.   2.   3. ]
 [ 1.5  0.  -3. ]]
[[ 10.  20.  30.]
 [ 15.   0. -30.]]
[[ 20.  40.  60.]
 [ 30.   0. -60.]]


dtype('float64')

In [76]:
# 스칼라 요소 간의 연산..? 무튼 수학적 연산에 도움을 줌
data1 = [1, 2, 3, 4]
data2 = [[1, 2, 3,], [10, 9, 8]]
data3 = [[1, 2, 3, 4], ['t', 'e', 's', 't']]


my_arr1 = np.array(data1)
my_arr2 = np.array(data2)
my_arr3 = np.array(data3)

# print(my_arr1)
# print(my_arr2)
# print(my_arr3)

# print(my_arr1.ndim) # N dimension, N 차원
# print(my_arr1.shape)
# print(my_arr2.dtype)
# print(my_arr2.shape)

print(f"{my_arr1.ndim}차원 배열\n데이터 타입:{my_arr1.dtype}\n")
print(f"{my_arr2.ndim}차원 배열\n데이터 타입:{my_arr2.dtype}\n{my_arr2.shape}의 크기를 가졌다.\n")
print(f"{my_arr3.ndim}차원 배열\n데이터 타입:{my_arr3.dtype}\n{my_arr3.shape}의 크기를 가졌다.\n")

1차원 배열
데이터 타입:int64

2차원 배열
데이터 타입:int64
(2, 3)의 크기를 가졌다.

2차원 배열
데이터 타입:<U21
(2, 4)의 크기를 가졌다.



In [77]:
my_arr1 = np.zeros(10)
# vector<int> my_arr(10, 0); 과 비슷함. 10개의 요소를 가진 배열을 만들고 모든 요소는 0으로 초기화
print(my_arr1)

my_arr2 = np.zeros((3, 6))
print(my_arr2) # 3행 6열의 배열을 만들고 모든 요소는 0으로 초기화

my_arr3 = np.ones((2, 2, 2))
print(my_arr3) # 2행 2열 2면의 배열을 만들고 모든 요소는 1로 초기화

my_arr4 = np.empty((2, 3))
print(my_arr4) # 2행 3열의 배열을 만들지만 쓰레기 값을 가지고 있음


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-323 4.4e-323 4.0e-323]]


In [78]:
print(np.arange(15))
print(list(range(0, 15)))



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


#### Array
입력 데이터(리스트, 튜플, 배열 또는 기타 시퀀스)를 데이터 유형을 추론하거나, 지정하여 N차 배열로 변환함. 입력 데이터를 복사함. array(시퀀스)
#### Asarray
입력값을 N차 배열로 변환하되, 입력값이 이미 N차 배열이면 새로 안 만듦. 불필요한 복사하지 않고 그대로 쓴다. asarray(시퀀스)
#### Arange
range랑 비슷한데 return 값이 리스트가 아니고 N차 배열 형태로 반환함. arange(입력값)
#### Full, Full_like
주어진 형태와 데이터 타입을 가진 배열 생성 후 입력받은 값으로 가득 채움 full(형태, 입력값)
#### Eye, identify
대각선에 1, 나머지는 모두 0인 N*N 크기의 정사각형 행렬
#### Zeros, zeros_like | Ones, ones_like

In [89]:
data = [[1,2,3], [4,5,6]]
a = np.array(data)
b = np.ones_like(a)
c = np.ones(a.shape)
print(b)
print(c)
d = np.full(a.shape, 5);
print(d)
e = np.eye(3)
print(e)
f = np.identity(3)
print(f)

[[1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
