# Numpy

## 0. Numpy 기능

넘파이에서 제공하는 기능
1. 빠른 배열 계산, 다차원 배열
2. 수학 함수
3. 배열 데이터 디스크에 작성 및 접근, 메모리 적재 파일 접근
4. 선형대수, 난수 생성, 푸리에 변환
5. C API

넘파이의 미쵸버린 성능 확인하기 ㄷㄷ

In [42]:
import numpy as np

# 길이 100만짜리 배열 투척 ㅋㅋ
numpy_arr = np.arange(1_000_000)
python_list = list(range(1_000_000))

In [43]:
%timeit numpy_arr * 2

2.25 ms ± 46.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [44]:
%timeit [x*2 for x in python_list]

43.1 ms ± 366 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


거이 머 최소 10배 이상 빠름

## 1. 다차원 배열

### 1.1 ndarray 선언과 특징

In [45]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]]) # array 함수 안에 리스트
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [46]:
print("========스칼라 연산========")
print(10*data)
print("========행렬 연산========")
print(data+data)
print("========모양========")
print(data.shape)
print("========배열 인스턴스의 자료형========")
print(data.dtype)
print("========차원========")
print(data.ndim)

========스칼라 연산========
[[ 15.  -1.  30.]
 [  0. -30.  65.]]
========행렬 연산========
[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]
========모양========
(2, 3)
========배열 인스턴스의 자료형========
float64
========차원========
2


### 1.2 여러가지 배열을 생성하는 함수

In [51]:
np.zeros((1,3,4)) # (1,3,4) 모양의 0으로 초기화된 배열

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [48]:
np.ones((3)) # 0 말고 1

array([1., 1., 1.])

In [49]:
np.empty((2,3)) # 초기화 되지 않은 배열을 작성. 그래서 아무 값이나 막 들어있음

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [58]:
np.full((2,3), 7) # 7로 초기화된 (2,3)배열 생성

array([[7, 7, 7],
       [7, 7, 7]])

In [59]:
temp = np.array([1.0, 2.0, 3.0])
np.zeros_like(temp) # ones_like, empty_like, full_like
# 주어진 배열의 모양과 똑같은 0, 1, empty, full 배열 생성

array([0., 0., 0.])

In [53]:
np.arange(10) # 파이썬 range 함수의 array 버전임

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
my_list = [1,2,3]
my_arr = np.asarray(my_list)
my_arr is my_list # False 입력 데이터가 ndarray가 아니면 ndarray이면 복사 X, ndarray 새로 만듬

my_arr2 = np.asarray(my_arr) # ndarray이므로 기본 배열을 그대로 참조
my_arr is my_arr2 # True 같은 메모리를 가르킴

True

In [ ]:
np.identity(4) # (4,4) 단위 행렬 생성

In [60]:
np.eye(5,6, k=2) # (5,6) 행렬에서 주대각선보다 2칸 위를 1로 채움

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

### 1.3 ndarray의 자료형

넘파이는 다양한 자료형을 지원한다
int, uint8, 16, 32, 64
float16, 32, 64, 128
object 파이썬 객체형. 보통 태뷸러 데이터 분석을 할때 문자열 자료형이 object로 나옴

In [ ]:
arr_float64 = np.array([1,2,3], dtype=np.float64) # 배정밀도(64비트) 지정. 딥러닝 시에는 반정밀도(16비트) 실수만 사용해도 성능에 문제없음
arr_float64.dtype

dtype('float64')

명시적으로 형 변환하기

In [62]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int64
float64


### 1.4 배열의 산술연산

In [66]:
arr = np.array([[1., 2., 3.], [4., 5., 6.,]])

arr*arr # 각 배열의 원소단위로 계산한다

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [68]:
1/arr # 스칼라와의 연산은 기본 행렬 연산과 똑같다

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [70]:
# 동일 크기의 배열간 비교연산은 불리언 값을 반환한다
arr2 = np.array([[1,2,10], [4,5,8]], dtype=np.float64)
arr2>arr

array([[False, False,  True],
       [False, False,  True]])

### 1.5 인덱싱과 슬라이싱

1차원 배열

In [75]:
arr = np.arange(10)

# 1차원 배열은 파이썬 리스트와 유사
print(arr[3:5])
arr[3:5] = 10
print(arr)

[3 4]
[ 0  1  2 10 10  5  6  7  8  9]


In [83]:
arr_slice = arr[3:5]
print(arr_slice)
arr_slice[0] = 3
print(arr)

[10 10]
[ 0  1  2  3 10  5  6  7  8  9]


다차원 배열

In [86]:
arr2d = np.array([[1,2,3], 
                  [4,5,6]], dtype=np.float64)

print(arr2d[0])      # 0번째 행
print(arr2d[0][1])   # 0번째 행, 1번째 열
print(arr2d[0, 1])    # 이렇게도 접근 가능

[1. 2. 3.]
2.0
2.0
